# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run pytest
 
on:
  push:
    branches: [ master , dev ]
  pull_request:
    branches: [ master , dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9']

    steps:
    - 
      uses: actions/checkout@v2
      
    - 
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_KEY_VAULT }} # Define secret variable in repository settings as per action documentation
        
    - 
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "dipvp"
        secrets: 'Azure-Blob-admin-key'
      id: myGetSecretAction
      
    - 
      name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - 
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        pip install azure-storage-blob
        pip install -e .
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - 
      name: Test with pytest
      run: |
        pytest tests/ --azBlobKey="${{ steps.myGetSecretAction.outputs.Azure-Blob-admin-key }}"
