# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package
 
on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - 
      name: Set up Python

      uses: actions/setup-python@v2
      with:
        python-version: '3.9.7'
        
    - 
      name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install setuptools wheel twine sphinx
        
    - 
      name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        ls
        #python setup.py sdist bdist_wheel
        #twine upload dist/*
    -
      name: Build doc
      run: |
        pip install .
        chmod 777 ./docs/Makefile
        pip install .
        cd docs && make html && \
        cp -a ./build/html/. ./  && \
        rm -r ./build

    -
      name: Commit changes
      run : |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add docs/\*
        git commit -m "Build docs"
        git push
