# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package
 
on:
  release:
    types: [published]
    
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - 
      uses: actions/checkout@v2
    - 
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_KEY_VAULT }} # Define secret variable in repository settings as per action documentation
        
    - 
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "dipvp"
        secrets: 'DevOps-token-read-write'
      id: myGetSecretAction
      
    - 
      name: Set up Python

      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - 
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine sphinx
        
    - 
      name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ steps.myGetSecretAction.outputs.DevOps-token-read-write }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/* --repository-url https://pkgs.dev.azure.com/Equinor/DIPVP/_packaging/ET_PSM/pypi/upload
    -
      name: Build doc
      run: |
        ./docs/make html
        cp -a ./docs/build/html/. /docs/
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add git add /docs/build/html/\*
        git commit -m "Build docs"
        git push
